# # Invalid
# start: [3,3]
# goal: [3,7]

# # Test
# start: [3, 3]
# goal: [3, 4]

# # Easy
# start: [7, 3]
# goal: [7, 26]

# # Moderate
# start: [20,45]
# goal: [31,43]

# # Hard
start: [3, 3]
goal: [3, 46]

sensor_range: 0.6 # distance (in m) the robot can sense
